CREATE TABLE PLAYER (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(100) NOT NULL,
    DateOfBirth DATE,
    PhoneNumber NVARCHAR(15),
    
);

CREATE TABLE BET (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    DrawTime DATETIME NOT NULL,
    ResultNumber INT CHECK (ResultNumber BETWEEN 0 AND 9),
);
CREATE TABLE PLAYER_BET(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	BET_ID INT ,
	PLAYER_ID INT,
	BetNumber INT CHECK (BetNumber BETWEEN 0 AND 9),
	isWinner BIT DEFAULT 0,
	FOREIGN KEY (BET_ID) REFERENCES BET(ID),
	FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(ID),
)